# Generated by Django 6.1.1 on 2026-09-29 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historyentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historyentry',
            options={'ordering': ['order', 'year'], 'verbose_name': 'History Entry', 'verbose_name_plural': 'History Entries'},
        ),
    ]
