# Generated by Django 6.1.1 on 2026-09-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_historyentry_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmingHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='farming/hero/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Farming Hero',
                'verbose_name_plural': 'Farming Hero',
            },
        ),
        migrations.CreateModel(
            name='FarmingUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='farming/updates/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Farming Update',
                'verbose_name_plural': 'Farming Updates',
                'ordering': ['-date', 'order'],
            },
        ),
    ]
