# Generated by Django 6.1.1 on 2026-09-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('children', "Children's Home"), ('school', 'Green Valley English School'), ('agriculture', 'Agriculture'), ('general', 'General')], default='general', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='updates/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Home Update',
                'verbose_name_plural': 'Home Updates',
                'ordering': ['-date', 'order'],
            },
        ),
    ]
